Geehy:
  APM32F1:
    APM32F103:
      APM32F103ZET6:
        Package: "LQFP144"
        Core: "Arm Cortex-M3"
        Frequency: 96
        Ram: 128
        Flash: 512
        IO: 112
        Voltage: { Max: 3.6, Min: 2.0 }
        Current: { Lowest: 1.9, Run: 421.0 }
        Temperature: { Max: 105.0, Min: -40.0 }
        Peripherals:
          ADC 12-bit: 21
          CAN: 1
          DAC 12-bit: 2
          FSMC: 1
          I2C: 2
          I2S: 2
          RTC: 1
          SDIO: 1
          SPI: 3
          Timer 16-bit: 8
          UART: 2
          USART: 3
          USB Device: 1
