name: 🔖 release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: 🔖 release repository
    runs-on: ubuntu-latest
    steps:
      - name: 🔖 create a recursive clone compressed file
        uses: csplink/action_release/@master
